name: Redeploy bastion

permissions:
  contents: read

on:
  schedule:
    - cron: "0 0 7,15,22,28 * *" # Runs on the 7th, 15th, 22nd, and 28th of any given month
  workflow_dispatch:

# NOTE: This is intended to periodically rotate bastion & its credentials.
# It's kind of a side effect of deploying, which we expect to happen roughly every three weeks.
# When we attempt to provision bastion, if its underlying AMI has changed, it will
# provision a new bastion and retire the old one.
jobs:
  redeploy-pya-staging-bastion:
    name: Redeploys bastion in pya staging
    runs-on: ubuntu-latest
    environment: pya-nonprod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Initialize OpenTofu for pya staging
        working-directory: ./tofu/config/staging.pya.fileyourstatetaxes.org
        run: tofu init

      - name: Apply changes to pya staging
        working-directory: ./tofu/config/staging.pya.fileyourstatetaxes.org
        run: tofu apply --auto-approve -target module.pya.module.bastion

  # redeploy-demo-efiler-api-bastion:
  #   name: Redeploys bastion in efiler-api demo
  #   runs-on: ubuntu-latest
  #   environment: efiler-api-demo
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #     - name: Set up AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v4
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1

  #     - name: Setup OpenTofu
  #       uses: opentofu/setup-opentofu@v1

  #     - name: Initialize OpenTofu for efiler-api demo
  #       working-directory: ./tofu/config/staging.pya.fileyourstatetaxes.org
  #       run: tofu init

  #     - name: Initialize OpenTofu for efiler api demo
  #       working-directory: ./tofu/config/demo.efiler-api.fileyourstatetaxes.org
  #       run: tofu init
  #     - name: Apply changes to efiler api demo
  #       working-directory: ./tofu/config/demo.efiler-api.fileyourstatetaxes.org
  #       run: tofu apply --auto-approve -target module.efiler_api.module.bastion

  redeploy-gyraffe-staging-bastion:
    name: Redeploys bastion in gyraffe staging
    runs-on: ubuntu-latest
    environment: gyraffe-nonprod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Initialize OpenTofu for gyraffe staging
        working-directory: ./tofu/config/staging.gyraffe.getyourrefund.org
        run: tofu init
      - name: Apply changes to gyraffe staging
        working-directory: ./tofu/config/staging.gyraffe.getyourrefund.org
        run: tofu apply --auto-approve -target module.gyraffe.module.bastion

  redeploy-pya-bastion:
    name: Redeploys bastion in pya
    runs-on: ubuntu-latest
    environment: pya-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1

      - name: Initialize OpenTofu for pya
        working-directory: ./tofu/config/pya.fileyourstatetaxes.org
        run: tofu init
      - name: Apply changes to pya
        working-directory: ./tofu/config/pya.fileyourstatetaxes.org
        run: tofu apply --auto-approve -target module.pya.module.bastion

      # - name: Initialize OpenTofu for gyraffe
      #   working-directory: ./tofu/config/gyraffe.getyourrefund.org
      #   run: tofu init
      # - name: Apply changes to gyraffe
      #   working-directory: ./tofu/config/gyraffe.getyourrefund.org
      #   run: tofu apply --auto-approve -target module.gyraffe.module.bastion
